name: 1- 自动发布版本
on:
  push:
    tags:
      - 'V*'

jobs:
  build:
    name: 打包发布
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: 构建发布包
      run: |
          sudo apt update -y
          sudo apt install jq cloc protobuf-compiler gcc-mingw-w64-x86-64 gcc-arm-linux-gnueabi -y
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          cloc ./
          chmod 755 ./gen_version.sh
          chmod +x ./gen_version.sh
          chmod 755 ./gen_proto.sh
          chmod +x ./gen_proto.sh
          chmod 755 ./release_pkg.sh
          chmod +x ./release_pkg.sh
          make
          bash ./release_pkg.sh

    - name: 上传发布包
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: _build/_release/rulex-*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
