name: 3- Windows构建测试
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install Chocolate
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString("https://community.chocolatey.org/install.ps1"))
          choco feature enable -n=allowGlobalConfirmation
  
      - name: Install Visualcpp-build-tools
        shell: powershell
        run: choco install visualcpp-build-tools -Y
  
      - name: Install golang
        shell: powershell
        run: |
            choco upgrade chocolatey
            choco install make -Y
            choco install golang --version 1.17.2 -Y
        
      - name: Build
        shell: powershell
        run: |
            git clone https://gitee.com/wwhai/rulex.git
            cd rulex
            go version
            make windows
               
