name: 4- Arm32-V7 构建测试

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Arm32-V7 构建测试
        run: |
              docker build -f ./.github/workflows/Dockerfile_arm32v7 . 
