name: BuildArm32

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BuildArm32
        id: docker_build
        uses: docker/build-push-action@v2
        run: |
              docker build -f .\Dockerfile_arm32v7 . 
