on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Windows Build Test

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2

      - name: Install Chocolate
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString("https://community.chocolatey.org/install.ps1"))
          choco feature enable -n=allowGlobalConfirmation
  
      - name: Install Visualcpp-build-tools
        shell: powershell
        run: choco install visualcpp-build-tools -Y
        
      - name: Install C Runtime
        shell: powershell
        run: choco install kb3118401 -Y
          
      - name: Install Make
        shell: powershell
        run: choco install make -Y
          
      - name: Install Cygwin
        shell: powershell
        run: choco install cygwin -Y
          
      - name: Install curl
        shell: powershell
        run: choco install curl -Y
          
      - name: Install jq
        shell: powershell
        run: choco install jq -Y
          
      - name: Install zip
        shell: powershell
        run: choco install zip -Y
          
      - name: Install unzip
        shell: powershell
        run: choco install unzip -Y
          
      - name: Install git
        shell: powershell
        run: choco install git -Y
          
      - name: Print Root Tree
        shell: powershell
        run: |
          TREE C:
          
      # - name: Install Erlang OTP-24
      #   shell: powershell
      #   run: choco install erlang -Y
          
      # - name: Build EMQX
      #   shell: powershell
      #   run: |
      #     $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64"
      #     set include="C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include"
      #     git clone https://github.com/emqx/emqx.git
      #     cd emqx
      #     make
          
