on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Windows Build Test

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2

      - name: ipconfig
        shell: powershell
        run: ipconfig

      - name: Install Chocolate
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString("https://community.chocolatey.org/install.ps1"))
          choco feature enable -n=allowGlobalConfirmation
  
      - name: Install Erlang Make
        shell: powershell
        run: choco install make -Y
          
      - name: Install Cygwin
        shell: powershell
        run: choco install cygwin -Y
          
      - name: Install curl
        shell: powershell
        run: choco install curl -Y
          
      - name: Install jq
        shell: powershell
        run: choco install jq -Y
          
      - name: Install zip
        shell: powershell
        run: choco install zip -Y
          
      - name: Install unzip
        shell: powershell
        run: choco install unzip -Y
          
      - name: Install git
        shell: powershell
        run: choco install git -Y
          
      - name: Install Erlang OTP-24
        shell: powershell
        run: choco install erlang -Y
          
      - name: Build EMQX
        shell: powershell
        run: |
          git clone https://github.com/emqx/emqx.git
          cd emqx
          make
          
