on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Windows Build Test

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2

      - name: Install Chocolate
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString("https://community.chocolatey.org/install.ps1"))
          choco feature enable -n=allowGlobalConfirmation
  
      - name: Install Visualcpp-build-tools
        shell: powershell
        run: choco install visualcpp-build-tools -Y

      - name: Install Make
        shell: powershell
        run: choco install make -Y
          
      - name: Install Cygwin
        shell: powershell
        run: choco install cygwin -Y
          
      - name: Install Visualcpp-build-tools
        shell: powershell
        run: choco install golang -Y
        
      - name: Build
        shell: powershell
        run: make windows
               
