name: RulexBuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
            sudo apt install jq -y
            go test -timeout 30s -run ^TestFullyRun$ rulex/test -v
            curl -q -s http://127.0.0.1:2580/api/v1/system | echo
