on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Windows Build Test

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2
      - name: ipconfig
        shell: powershell
        run: ipconfig
