name: RulexBuild

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build && Test
        run: |
            sudo apt update -y
            sudo apt install jq cloc protobuf-compiler -y
            cloc ./
            chmod 755 ./gen_version.sh
            chmod +x ./gen_version.sh
            chmod 755 ./gen_proto.sh
            chmod +x ./gen_proto.sh
            make
            go test -timeout 30s -run ^TestFullyRun$ rulex/test -v