on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Windows Build Test

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1

      - name: ipconfig
        run: ipconfig