name: BuildArm32

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BuildArm32
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile_arm32v7
          push: false
          tags: wwhai/rulex:latest
