name: Sync to Gitee
on: [push]
jobs:
  sync:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.W_RSA_PRIV }}
      with:
        # 来源仓库
        source-repo: "git@github.com:wwhai/rulex.git"
        # 目标仓库
        destination-repo: "git@gitee.com:wwhai/rulex.git"